export { AboutMain } from './about-main/about-main';
export { Button } from './button/Button';
export { Slider } from './carousel/carousel';
export { Contacts } from './contacts/contacts';
export { Footer } from './footer/footer';
export { Header } from './header/header';
export { JoinUs } from './join-us/join-us';
export { NewsList } from './news-list/news-list';
export { NotFound } from './not-found/not-found';